# 1. 보안 데이터 (Secret)
apiVersion: v1
kind: Secret
metadata:
  name: sensor-secret
type: Opaque
stringData:
  INFLUXDB_TOKEN: "m7B0P2yETOdQ3M70i9qAk3GvpiEolGak0oQoT27rqnXI5VXvPS_DkK7tqG7-k5Kk_5PQr-MukXFGOsaYN_AD0g=="
  # 서비스 이름인 'mariadb-svc'를 사용합니다.
  MARIADB_URL: "mysql+pymysql://sensor_user:sensor_password@mariadb-svc:3306/sensor_db"
