# 08-ai.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-ai
  template:
    metadata:
      labels:
        app: sensor-ai
    spec:
      nodeSelector:
        node-role: ai
      containers:
        - name: sensor-ai
          image: sensor-ai:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
          env:
            - name: MODEL_DIR # 파이썬 코드에서 읽을 환경 변수
              value: "/app/models"
          envFrom:
            - configMapRef:
                name: sensor-config
            - secretRef:
                name: sensor-secret
          # 🌟 컨테이너 내부의 폴더와 볼륨을 연결
          volumeMounts:
            - name: model-storage
              mountPath: /app/models
          resources:
            limits:
              memory: "4Gi"
              cpu: "2000m"
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: ai-model-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sensor-ai-svc
spec:
  selector:
    app: sensor-ai
  ports:
    - port: 8002 # 🌟 포트 수정
      targetPort: 8002
---
# 🌟 1. AI 모델을 저장할 가상 하드디스크(PVC) 생성
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-model-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # 모델 크기에 따라 넉넉하게 잡아주세요
---
