apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-sql
data:
  init.sql: |
    -- 이 내용은 DB가 처음 생성될 때 한 번만 자동 실행됩니다.
    CREATE DATABASE IF NOT EXISTS sensor_db;
    USE sensor_db;

    CREATE TABLE IF NOT EXISTS sensor (
        id INT AUTO_INCREMENT PRIMARY KEY,
        sensor_name VARCHAR(50) NOT NULL,
        location VARCHAR(100),
        status VARCHAR(20)
    );

    CREATE TABLE IF NOT EXISTS model (
        id INT AUTO_INCREMENT PRIMARY KEY,
        model_name VARCHAR(100) NOT NULL,
        version VARCHAR(20),
        ai_accuracy FLOAT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      nodeSelector:
        node-role: data # 🌟 Data 노드 지정
      containers:
        - name: mariadb
          image: mariadb:10.11
          ports:
            - containerPort: 3306
              hostPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "sensor_root_password"
            - name: MARIADB_DATABASE
              value: "sensor_db"
            - name: MARIADB_USER
              value: "sensor_user"
            - name: MARIADB_PASSWORD
              value: "sensor_password"
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
            - name: init-sql-volume
              mountPath: /docker-entrypoint-initdb.d
          resources:
            limits:
              memory: "800Mi"
              cpu: "500m"
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
        - name: init-sql-volume
          configMap:
            name: mariadb-init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
